development:
  image_urls:
    -
      name: 'cat'
      url: '/images/cat.svg'
    -
      name: 'diamond'
      url: '/images/diamond.svg'
    -
      name: 'thumb'
      url: '/images/thumb.svg'

  rule_names:
    -
      name: 'Успешное прохождение всех тестов определенной категории'
      value: 'category'
    -
      name: 'Успешное прохождение всех тестов определенного уровня'
      value: 'level'
    -
      name: 'Успешное прохождение теста с первой попытки'
      value: 'attempt'

production:
  image_urls:
    -
      name: 'cat'
      url: '/images/cat.svg'
    -
      name: 'diamond'
      url: '/images/diamond.svg'
    -
      name: 'thumb'
      url: '/images/thumb.svg'

  rule_names:
    -
      name: 'Успешное прохождение всех тестов определенной категории'
      value: 'category'
    -
      name: 'Успешное прохождение всех тестов определенного уровня'
      value: 'level'
    -
      name: 'Успешное прохождение теста с первой попытки'
      value: 'attempt'
